// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class Order : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Order\",\"namespace\":\"avro\",\"fields\":[{\"name\":\"orderId\",\"t" +
				"ype\":\"int\"},{\"name\":\"strings\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":" +
				"\"date_\",\"type\":\"long\"},{\"name\":\"total_cost\",\"type\":\"int\"}]}");
		private int _orderId;
		private IList<System.String> _strings;
		private long _date_;
		private int _total_cost;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Order._SCHEMA;
			}
		}
		public int orderId
		{
			get
			{
				return this._orderId;
			}
			set
			{
				this._orderId = value;
			}
		}
		public IList<System.String> strings
		{
			get
			{
				return this._strings;
			}
			set
			{
				this._strings = value;
			}
		}
		public long date_
		{
			get
			{
				return this._date_;
			}
			set
			{
				this._date_ = value;
			}
		}
		public int total_cost
		{
			get
			{
				return this._total_cost;
			}
			set
			{
				this._total_cost = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.orderId;
			case 1: return this.strings;
			case 2: return this.date_;
			case 3: return this.total_cost;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.orderId = (System.Int32)fieldValue; break;
			case 1: this.strings = (IList<System.String>)fieldValue; break;
			case 2: this.date_ = (System.Int64)fieldValue; break;
			case 3: this.total_cost = (System.Int32)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
